---
title: Traverse
timezone: Europe/Kiev
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
    permalink: "/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: products
  values:
    layout: product
description: "Спорядження для складних ситуацій."
baseurl: 
url: http://www.jekyll-store.com
defaultAddress:
  country: UA
payment:
  currency: UAH
  hook: https://jekyll-store-microservice.herokuapp.com/purchase
tracking_id: UA-62379004-1
image_prefix: http://res.cloudinary.com/jekyll-store/
paymillPublicKey: 323027826220f6ed944b96a1a47e35a0
wake_up: http://jekyll-store-microservice.herokuapp.com/ping
disqus_shortname: jekyll-store
accounting:
  symbol: "£"
  format: "%s%v"
  decimal: "."
  thousand: ","
  precision: 2
prose:
  ignore:
  - _includes
  - _layouts
  - assets
  - json
  - node_modules
  - pages
  - ".gitignore"
  - _config.yml
  - CNAME
  - Gemfile
  - package.json
  - README.md
  metadata:
    _products:
    - name: name
      field:
        element: text
        label: Name
        help: Must be unique
    - name: type
      field:
        element: select
        label: Type
        options:
        - value: "Чохли для бронежилетів"
        - value: "Розгрузки"
        - value: "Рюкзаки"
        - value: "Підсумки"
        - value: "Аптечки"
        - value: "Комплекти"
    - name: color
      field:
        element: select
        label: Color
        options:
        - value: A-TACS FG™
        - value: A-TACS AU™
        - value: Multicam™
        - value: Ukrpixel®
        - value: Coyote
        - value: Olive
        - value: Black
    - name: image
      field:
        element: text
        label: Image
    - name: big_image
      field:
        element: text
        label: Big Image
permalink: blog/:title
sass:
  sass_dir: "/assets/_sass"
  style: compressed
exclude:
- node_modules
- Gemfile
- Gemfile.lock
- README.md
- CNAME
- package.json
